import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/utils/Navbar'
import Container from '@/components/utils/Container'
import HeroSection from '@/components/HeroSection'
import AboutSection from '@/components/AboutSection'


export default function Home() {
  return (
    <>
      <Head>
        <title>Joshuajee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="text-[#8892B0] ">

        <HeroSection />

        <AboutSection />


      </main>
    </>
  )
}
